name: Deploy Foundation Infrastructure

on:
  pull_request:
    branches:
      - main
    paths:
      - 'foundation/**'
  push:
    branches:
      - main
    paths:
      - 'foundation/**'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Checkout code
        uses: actions/checkout@v6

      # https://github.com/gruntwork-io/terragrunt-action
      - name: Setup Terragrunt
        uses: gruntwork-io/terragrunt-action@v3

      # https://github.com/aws-actions/configure-aws-credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@main
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Run terragrunt plan
        working-directory: foundation/deployments/organization
        run: terragrunt plan

      - name: Run terragrunt apply
        if: github.event_name == 'push'
        working-directory: foundation/deployments/organization
        run: terragrunt apply --auto-approve